### ISSUE TITLE
How can I handle an image whose URL will be fetched later?

### ISSUE THREAD

**Issue by jlstr** [andrefarzat/ng-jcrop#52] opened 2016-05-10 16:54 UTC
Hello, I would like to know how can I handle an image url that I receive dynamically. For example:

```
  app.controller('CropController',
    function($scope) {
      $scope.obj = {
        url: '',
        coords: [ 100, 100, 200, 200, 100, 100 ],
        thumbnail: false
      };

      $scope.$on('cropImageUrl', function(event, url) {
        // Here I receive the Image's actual URL passed from another Controller
        $scope.obj.url = url;
      });
    }
  );
```

How can I make it load in the HTML once the actual URL is received?

```
<div ng-jcrop="object.url" selection="obj.coords" thumbnail="obj.thumbnail"></div>
```

Currently, the image will not display. Please help

-J

**Comment by andrefarzat** [comment] 2016-05-10 19:34
@jlstr As a quick workaround, you can broadcast the `JcropChangeSrc` event via `$rootScope` (see: https://github.com/andrefarzat/ng-jcrop/blob/master/ng-jcrop.js#L125)

Can I ask you to try:
```js
$scope.$on('cropImageUrl', function(event, url) {
    // Here I receive the Image's actual URL passed from another Controller
    $scope.obj.url = url;
    $rootScope.$broadcast('JcropChangeSrc', $scope.obj.url, 'default');
});

**Comment by jlstr** [comment] 2016-05-10 20:06
Thank you very much for the reply @andrefarzat! I will have to try your solution a little later (I had to move on to other tasks since this one was taking so long). I sincerely hope it works Jcrop is generally a nice cropping tool.

**Comment by andrefarzat** [comment] 2016-05-10 21:20
@jlstr let me know if you succeeded or not 😸

**Comment by jlstr** [comment] 2016-05-11 05:48
I'll definitely let you know, my employer has switched priorities so, I'll have to get back in a bit. Thank you once again for your support.

**Comment by kelkes** [comment] 2016-10-08 07:37
`$rootScope.$broadcast('JcropChangeSrc', $scope.obj.url, 'default');`

That fixed a bug i've been hunting for 2 days now. Thanks!

I was uploading an image and after that updating den src but the image was displayed as a 20x20px picture instead... (IE only).

After adding the broadcast it finally worked!

**Comment by andrefarzat** [comment] 2016-10-09 05:27
@kelkes so everything is fine? :)
If yes, I gonna close this issue

**Comment by kelkes** [comment] 2016-10-09 05:29
Its working but i would consider it a workaround. At least this should be added to the documentation:)

**Comment by andrefarzat** [comment] 2016-10-09 05:34
It is a workaround :(
I will look better on this to see if I can avoid it.
If not, I follow your suggestion and add it to the docs.
(Will see this Tuesday, it's thanksgiven in Canada this Monday :smily_cat: )

**Comment by kelkes** [comment] 2016-10-10 08:59
After some more intense testing by my client the issue is still there...

That happens after changing the src

![screen shot 2016-10-07 at 16 17 23](https://cloud.githubusercontent.com/assets/204445/19231103/7690944c-8ed8-11e6-80a5-6ac07ed52976.png)

```
$scope.passportPhoto.coords = [0, 0, 6000, 6000, 2000, 1500];
$scope.passportPhoto.src = baseUrl + 'api/internal-files/' + result.data.fileName;
$rootScope.$broadcast('JcropChangeSrc', $scope.passportPhoto.src, 'default');
```

**Closed** 2017-01-06 03:45 UTC
